# Generated by Django 2.0.5 on 2018-05-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Random',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aRandomText', models.CharField(max_length=100)),
                ('creation_date', models.DateTimeField(verbose_name='doc')),
            ],
        ),
    ]
